cowprotocol/cms

.github/workflows/docker.yml
Publish docker images automatically when pushing to main or tagging a new version
Config copied from this other PR:
https://github.com/cowprotocol/watch-tower/pull/61
Temporarily, I forced actions to run on PR commits. This is how I tested the deployment (see https://github.com/cowprotocol/cms/pull/8/commits/eb2b675e396c010c5298cf2f8a250d33e7d3f0e7):
- Deployment: https://github.com/cowprotocol/cms/actions/runs/6372812813
See published package: https://github.com/cowprotocol/cms/pkgs/container/cms
=> Publish docker images

.npmignore, package.json, src/lib.ts, tsconfig.lib.json
Adapts the package.json to allow to build a new library `@cowprotocol/cms`
Includes also the typescript configuration.
After the changes, I published a new library:
https://www.npmjs.com/package/@cowprotocol/cms
For that, I used `npm publish --access public`
It has given me a headache (as always we create a new library) when I wanted to have a custom README.md
As this library is internal, allow me to use the strapi README also for the library. Ideally I would love to override it with another one, but NPM don't make it very easy! 
Build Library:
`yarn build:lib`
Pretend you publish the library, see the output of:
`npm publish --dry-run`
=> Create library @cowprotocol/cms

package.json, src/lib.ts, yarn.lock
Publishes a client to access the CMS
Make uses of the new CMS types, and build a client using `openapi-fetch`, which is the companion library for  `openapi-typescript`
=> Publish client

.env.example, src/api/notification-template/content-types/notification-template/schema.json, src/api/notification/services/notification.ts, src/api/telegram-subscription/content-types/telegram-subscription/schema.json, src/api/telegram-subscription/controllers/telegram-subscription.ts, src/api/telegram-subscription/routes/telegram-subscription.ts, src/api/telegram-subscription/services/telegram-subscription.ts, src/api/telegram-subscription/types.ts, src/extensions/documentation/documentation/1.0.0/full_documentation.json
1. Get all telegram subscriptions for an account
```
http://localhost:1337/api/tg-subscriptions/0xfb3c7eb936cAA12B5A884d612393969A557d4307
```
2. Add a subscription
```
fetch('http://localhost:1337/api/add-tg-subscription', {method: 'POST', body: JSON.stringify({account: '0xfb3c7eb936cAA12B5A884d612393969A557d4307', data: {
auth_date: 1715154310,
first_name: "xxxx",
hash: "1f2b9a99f5162f9b72b78b85c4a16d44c8f85d0a69eb4a5c50082d3fdb64b541",
id: 11111111,
photo_url: "......",
username: "sssss"
}})})
```
3. Send notifications to telegram
```
http://localhost:1337/api/send-tg-notifications/0xfb3c7eb936cAA12B5A884d612393969A557d4307
```
=> feat: add telegram subscription

src/lib.ts
Add possibility to the CMS lib to add an API KEY and some optional headers
=> Allow to set your own headers and your API KEY

src/api/notification/controllers/notification.ts, src/api/notification/services/notification.ts, src/api/telegram-subscription/controllers/telegram-subscription.ts, src/api/telegram-subscription/routes/telegram-subscription.ts, src/api/telegram-subscription/services/telegram-subscription.ts, src/extensions/documentation/documentation/1.0.0/full_documentation.json
1. Send telegram notifications to all subscribers: http://localhost:1337/api/send-tg-notifications
2. Get subscriptions for several accounts: http://localhost:1337/api/tg-subscriptions/0x1,0x2,0x3
=> feat: get subscriptions for several accounts

Dockerfile
The build fails because of node version: 
https://github.com/cowprotocol/cms/actions/runs/9578191698/job/26407909811#step:5:513
=> chore: up node version

src/api/notification/services/notification.ts
`/api/notification-list` endpoint was not considering different cases for `account` parameter.
Now it select notifications for both original and lowercased.
=> fix: search notifications for account with any case

package.json, patches/@strapi+plugin-upload+4.13.3.patch, yarn.lock
Fix for the error:
```
TypeError: Failed to construct 'URL': Invalid URL
at appendSearchParamsToUrl (main.bd958251.js:35710:18)
at ImageAssetCard (main.bd958251.js:28243:72)
```
=> fix: path upload plugin to fix URL issue

src/api/network/content-types/network/schema.json, src/api/network/controllers/network.ts, src/api/network/documentation/1.0.0/network.json, src/api/network/routes/network.ts, src/api/network/services/network.ts, src/api/solver/content-types/solver/schema.json, src/api/solver/controllers/solver.ts, src/api/solver/documentation/1.0.0/solver.json, src/api/solver/routes/solver.ts, src/api/solver/services/solver.ts, src/extensions/documentation/documentation/1.0.0/full_documentation.json
Allow to add our supported networks to the CMS.
Model solvers.
After merging the PR we should make a new step in the process to add new networks
Run locally, and try to create the networks and a solver
=> Add solvers

src/api/environment/content-types/environment/schema.json, src/api/environment/controllers/environment.ts, src/api/environment/documentation/1.0.0/environment.json, src/api/environment/routes/environment.ts, src/api/environment/services/environment.ts, src/api/network/content-types/network/schema.json, src/api/solver-network/content-types/solver-network/schema.json, src/api/solver-network/controllers/solver-network.ts, src/api/solver-network/documentation/1.0.0/solver-network.json, src/api/solver-network/routes/solver-network.ts, src/api/solver-network/services/solver-network.ts, src/api/solver/content-types/solver/schema.json, src/extensions/documentation/documentation/1.0.0/full_documentation.json
Improves the modeling of solvers.
Moves the addresses from the solver entity to a new `solver-network` one. This way, we avoid replication of data.
These are the changes
We add a master record for the environments
This info has been moved
This entity maps a solver, to a network and a environment. It includes information about the address and payoutAddress
Run it locally and test creating a few solvers and solver networks
=> Remodel solvers

README.md, package.json, src/api/bonding-pool/content-types/bonding-pool/schema.json, src/api/bonding-pool/controllers/bonding-pool.ts, src/api/bonding-pool/documentation/1.0.0/bonding-pool.json, src/api/bonding-pool/routes/bonding-pool.ts, src/api/bonding-pool/services/bonding-pool.ts, src/api/solver-bonding-pool/content-types/solver-bonding-pool/schema.json, src/api/solver-bonding-pool/controllers/solver-bonding-pool.ts, src/api/solver-bonding-pool/documentation/1.0.0/solver-bonding-pool.json, src/api/solver-bonding-pool/routes/solver-bonding-pool.ts, src/api/solver-bonding-pool/services/solver-bonding-pool.ts, src/api/solver/content-types/solver/schema.json, src/extensions/documentation/documentation/1.0.0/full_documentation.json, src/gen/types.ts
Add Bonding Pool content type, as well as Solver Bonding Pool, for creating the relationships with the solvers.
=> feat: add bonding pool and related content types

src/api/tax-free-asset/content-types/tax-free-asset/schema.json, src/api/tax-free-asset/controllers/tax-free-asset.ts, src/api/tax-free-asset/documentation/1.0.0/tax-free-asset.json, src/api/tax-free-asset/routes/tax-free-asset.ts, src/api/tax-free-asset/services/tax-free-asset.ts, src/extensions/documentation/documentation/1.0.0/full_documentation.json
A new collection which contains a list of assets that should be free from volume fee in CoW Swap
- `One or two (comma separated) token ids. If one, then this token will be free from fees in any trade. If two, then only this specific pair will be free from fees.` - description to `tokenIds` field in view settings
- `find` permission to `Public` role
=> feat: add collection for assets that free from fees

.nvmrc, package.json, src/api/announcement/content-types/announcement/schema.json, src/api/announcement/controllers/announcement.ts, src/api/announcement/documentation/1.0.0/announcement.json, src/api/announcement/routes/announcement.ts, src/api/announcement/services/announcement.ts, src/extensions/documentation/documentation/1.0.0/full_documentation.json
Add `Announcement` model
Local testing via postman/curl, querying the entries with: `http://localhost:1337/api/announcements?populate[networks][fields][0]=chainId&populate[environments][fields][0]=name&fields[0]=text&fields[1]=isCritical`
Response:
```
{
"data": [
{
"id": 1,
"attributes": {
"text": "Test _announcement_ announcement with an [internal link](#/swap/1/usdc)",
"isCritical": false,
"networks": {
"data": [
{
"id": 2,
"attributes": {
"chainId": 100
}
},
{
"id": 1,
"attributes": {
"chainId": 1
}
}
]
},
"environments": {
"data": [
{
"id": 1,
"attributes": {
"name": "barn"
}
},
{
"id": 2,
"attributes": {
"name": "prod"
}
}
]
}
}
},
{
"id": 2,
"attributes": {
"text": "**Critical** announcement!!!",
"isCritical": true,
"networks": {
"data": [
{
"id": 2,
"attributes": {
"chainId": 100 …
```
=> feat: announcements

config/server.ts
Marketing is trying to upload a big file of notifications and the request gets failed every time because of 504 http error.
In order to fix that, I've increased the server timeout limit up to 2 mins.
https://www.linkedin.com/pulse/extending-request-timeout-strapi-quick-configuration-guide-pathak-ykdxc/
=> chore: set server timeout 2 mins

src/api/tax-free-asset/content-types/tax-free-asset/schema.json, src/extensions/documentation/documentation/1.0.0/full_documentation.json
While locally there are no issues, inserting long values into `tokenIds` field causes the operation to fail
The max char length of the string field is 255, while the text field has no limits.
=> feat: use text rather than string for tokenIds field type

src/api/solver-bonding-pool/content-types/solver-bonding-pool/schema.json, src/api/solver-network/content-types/solver-network/schema.json, src/api/solver/content-types/solver/schema.json, src/extensions/documentation/documentation/1.0.0/full_documentation.json
This PR extends #48 to include both whitelisting and vouching information on the solver-network relation. It also updates the solver-bonding-pool relation to indicate whether it is a full bonding pool or a reduced bonding pool and updates the solver model to indicate whether or not the solver pays a service fee.
It also adds flags to the solver-network and solver models to indicate whether a solver is colocated and whether a solver's address is colocated.
=> feat: Update solver models to include vouching, whitelisting, and service fee

config/cron-tasks.ts, src/api/notification/controllers/cleanup.ts, src/api/notification/routes/cleanup.ts, src/api/notification/services/cleanup.ts, src/extensions/documentation/documentation/1.0.0/full_documentation.json
Add a way to manually trigger the notification clean up.
The cronjob has been added for a few days, but the notifications had not been cleaned up.
Since the strapi cloud logs are quite bad to navigate, this should give instant feedback on what's wrong.
1. Create a new API token with the permission `Notification > cleanup > cleanupExpiredNotifications`: 
2. Make POST request containing the header: `authorization: bearer <api key>`
* The request should succeed and return the response.
Example of a successful response:
```
{
"data": {
"success": true,
"deletedCount": 0
}
}
```
Example of an error response:
```
{
"data": {
"success": false,
"error": "This is a test error"
}
}
```
=> feat: manually trigger notification

src/api/notification/services/cleanup.ts
After https://github.com/cowprotocol/cms/pull/58, it's possible to see that the cleanup is failing because too much is being deleted at once.
This change splits it into 1k batches.
Same as #58
=> feat: delete notifications in batches of 1k

src/api/telegram-subscription/controllers/telegram-subscription.ts, src/api/telegram-subscription/routes/telegram-subscription.ts, src/extensions/documentation/documentation/1.0.0/full_documentation.json
We need a method to check if a given blockchain account already subscribed to the Telegram account.
We already have this check in `addSubscription`, just moved it to a separate method in order to call the check before adding subscription.
=> feat: check telegram subscriptions

src/api/telegram-subscription/controllers/telegram-subscription.ts, src/api/telegram-subscription/routes/telegram-subscription.ts, src/api/telegram-subscription/services/telegram-subscription.ts, src/extensions/documentation/documentation/1.0.0/full_documentation.json
Added a new method to unsubscribe an account from Telegram notifications.
The method is protected with `checkSubscription`, so only when user has a valid TG authorization they can perform the unsubscription.
=> feat(notifications): add subscription removal method
